### ISSUE TITLE
Issue at line 93

### ISSUE THREAD

**Issue by vlat0101** [Sp1l/PhotoVoltaic#1]
Hi,

I'm a GoodWe inverter owner and found your script. I'm trying to implement it and get the following.

root@:~ # ./goodwe2PVoutput.sh
./goodwe2PVoutput.sh: 93: Syntax error: "}" unexpected (expecting "then")

The hist script works great btw but this would also be very handy.

Hope you can help,
Vlat

**Comment by Sp1l** [comment]
Thanks for reporting!

**Comment by Sp1l** [comment]
Don't know if you're still using this, but I just added a new script using the new semsportal and API

**Comment by vlat0101** [comment]
No I am not, I have just moved house and don't have solar yet. TBH I think I will go with Fronius next time and that will make connecting to web services much easier.
