### ISSUE TITLE
Trying to run on synology

### ISSUE THREAD

**Issue by roviaro** [Sp1l/PhotoVoltaic#3]
Trying to run the script on my synology NAS.

It appears that the date command on my NAS does not have the -j option.

mktemp: too few X's in template ‘goodwe2PVoutput-hist.sh’
Error: Date "2016-05-27" invalid, format YYYY-MM-DD

Any ideas on this? My NAS is running 24h so I was planning to run the scripts there.

Kind regards, Rob

**Comment by Sp1l** [comment]
Don't know if you're still using this, but I just added a new script using the new semsportal and API
