### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by scorbisiero** [Sp1l/PhotoVoltaic#4]
Hi,
Sorry, I had no idea what better title to choose.. I'm having difficulties with the POST bit, it works successfully but I'm returned just 0 in the YAxis.

> "YAxis": "{name:quot;PGrid(W)quot;,data:[0,0,0,0,0,0,0,0 and so on..

When I'm in GoodWe though, I can see the graph for the day **and** can also export the day and see every single minute there. I'm getting lost.

Note that I'm trying to grab this with PowerShell and not linux, but the method's the same. To be sure, I tried an app that does the post rather than from command line and I'm getting exactly the same results. I'm just wondering if this is still working for you guys..

Cheers

**Comment by scorbisiero** [comment]
Alright, I had the weirdest issue.. but found the solution: The problem was with the text I input in the POST. It was EXACTLY the same (by eye), but a string comparison showed they were actually different, so the SN I was feeding wasn't being accepted.

One thing you may find interesting, I chose to go for PowerStationReport/QueryTypeChangedFor5Minutes instead of PowerStationReport/QueryTypeChanged. That one gives me a 5 minutes timespan whilst the other would give me 10 minutes.

Next thing I'm gonna try to do, after I sort the output is trying to export the file generated and see if I can read it and get that sort of output (which is updated every 61 seconds).

Thanks

**Comment by Sp1l** [comment]
It is working again now.
Planning to add some notification via mail. Apparently I'm not so interested in the outputs, they happen anyway 😄

**Comment by Sp1l** [comment]
Don't know if you're still using this, but I just added a new script using the new semsportal and API

**Comment by scorbisiero** [comment]
Hey, yep I'm still "sort of" using it. I'm on Windows and had to build a powershell version of it, but mine still works with the old setup?
Here's what I'm using and how I did it:
https://www.itdroplets.com/get-goodwe-data-with-powershell/

Definitely interested in seeing if your updated version is better and could save some traffic. I barely check my web interface to be honest, it was fun in the beginning, now after 2.5 years with the solar panels, I'm ok with just the daily mails I get.
The only issue I've had last year was when GoodWe switched from http to https.
